---
title: "Anly 545- Final Presentation"
author: "Anisha Beria & Vishrut Rai Khatri"
date: "7/8/2021"
output:
  html_document: default
---
---

```{r setup, include=FALSE}
student= read.csv("/Users/anisha/Downloads/StudentData.csv")
```

```{r}

library(ggplot2)
library(ggpubr)
library(mosaic)
library(stats)
library(corrplot)
library(readr)
library(vcd)
library(ISLR)

summary(student)
head(student)


colnames(student)

# [1] "school"     "sex"        "age"        "address"    "famsize"    "Pstatus"    "Medu"       "Fedu"       "Mjob"      
#[10] "Fjob"       "reason"     "guardian"   "traveltime" "studytime"  "failures"   "schoolsup"  "famsup"     "paid"      
#[19] "activities" "nursery"    "higher"     "internet"   "romantic"   "famrel"     "freetime"   "goout"      "Dalc"      
#[28] "Walc"       "health"     "absences"   "G1"         "G2"         "G3"   

# Attributes for both student-mat.csv (Math course) and student-por.csv (Portuguese language course) datasets:
#1 school - student's school (binary: "GP" - Gabriel Pereira or "MS" - Mousinho da Silveira)
#2 sex - student's sex (binary: "F" - female or "M" - male)
#3 age - student's age (numeric: from 15 to 22)
#4 address - student's home address type (binary: "U" - urban or "R" - rural)
#5 famsize - family size (binary: "LE3" - less or equal to 3 or "GT3" - greater than 3)
#6 Pstatus - parent's cohabitation status (binary: "T" - living together or "A" - apart)
#7 Medu - mother's education (numeric: 0 - none,  1 - primary education (4th grade), 2 – 5th to 9th grade, 3 – secondary education or 4 #– higher education)
#8 Fedu - father's education (numeric: 0 - none,  1 - primary education (4th grade), 2 – 5th to 9th grade, 3 – secondary education or 4 #– higher education)
#9 Mjob - mother's job (nominal: "teacher", "health" care related, civil "services" (e.g. administrative or police), "at_home" or #"other")
#10 Fjob - father's job (nominal: "teacher", "health" care related, civil "services" (e.g. administrative or police), "at_home" or #"other")
#11 reason - reason to choose this school (nominal: close to "home", school "reputation", "course" preference or "other")
#12 guardian - student's guardian (nominal: "mother", "father" or "other")
#13 traveltime - home to school travel time (numeric: 1 - <15 min., 2 - 15 to 30 min., 3 - 30 min. to 1 hour, or 4 - >1 hour)
#14 studytime - weekly study time (numeric: 1 - <2 hours, 2 - 2 to 5 hours, 3 - 5 to 10 hours, or 4 - >10 hours)
#15 failures - number of past class failures (numeric: n if 1<=n<3, else 4)
#16 schoolsup - extra educational support (binary: yes or no)#
#17 famsup - family educational support (binary: yes or no)
#18 paid - extra paid classes within the course subject (Math or Portuguese) (binary: yes or no)
#19 activities - extra-curricular activities (binary: yes or no)
#20 nursery - attended nursery school (binary: yes or no)
#21 higher - wants to take higher education (binary: yes or no)
#22 internet - Internet access at home (binary: yes or no)
#23 romantic - with a romantic relationship (binary: yes or no)
#24 famrel - quality of family relationships (numeric: from 1 - very bad to 5 - excellent)
#25 freetime - free time after school (numeric: from 1 - very low to 5 - very high)
#26 goout - going out with friends (numeric: from 1 - very low to 5 - very high)
#27 Dalc - workday alcohol consumption (numeric: from 1 - very low to 5 - very high)
#28 Walc - weekend alcohol consumption (numeric: from 1 - very low to 5 - very high)
#29 health - current health status (numeric: from 1 - very bad to 5 - very good)
#30 absences - number of school absences (numeric: from 0 to 93)

# these grades are related with the course subject, Math or Portuguese:
#31 G1 - first period grade (numeric: from 0 to 20)
#31 G2 - second period grade (numeric: from 0 to 20)
#32 G3 - final grade (numeric: from 0 to 20, output target)

#Distribution of parents' education level

summary(student$Medu)

#  Min.  1st Qu.  Median  Mean   3rd Qu.    Max. 
# 0.000   2.000   2.000   2.515   4.000   4.000 

hist(student$Medu, breaks = 5)

summary(student$Fedu)

# Min.   1st Qu.  Median  Mean   3rd Qu.    Max. 
# 0.000   1.000   2.000   2.307   3.000   4.000 

hist(student$Fedu, breaks = 5)

#Distribution of G3 - Indicators of students' academic success

summary(student$G3)
# Min.   1st Qu.  Median   Mean  3rd Qu.    Max.
#  0.00   10.00   12.00   11.91   14.00   19.00 

hist(student$G3)

#Distribution of Weekly study time

summary(student$studytime)
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#  1.000   1.000   2.000   1.931   2.000   4.000 

boxplot(student$studytime, breaks = 5)

#Distribution of Extra educational support

table(student$schoolsup)
# no  yes 
#581  68 


#Correlation Plots for Numeric Values

df1 = subset(student, select=c(3, 7, 8, 13:15, 24:33))
head(df1)
corrplot(cor(df1))

#Parents' Education and G3 Scores

glm.fit = glm(G3 ~ Medu + Fedu, data = student)
glm.fit
summary(glm.fit)

#Parents' Education and Study Time

glm.fit1 = glm(studytime ~ Medu + Fedu, data = student)
glm.fit1
summary(glm.fit1)

# Parents' Education and School Support

mosaic(~schoolsup + Medu, data = student, shade=TRUE, legend = TRUE, labeling = labeling_values)

mosaic(~schoolsup + Fedu, data = student, color = TRUE, shade=TRUE, legend = TRUE, labeling = labeling_values)

mosaic(~schoolsup + Medu + Mjob, data = student, shade=TRUE, legend = TRUE, labeling = labeling_values, direction = "v", rot_labels=c(0,90,90), tl.cex = 0.5)

mosaic(~schoolsup + Fedu + Fjob, data = student, shade=TRUE, legend = TRUE, labeling = labeling_values, direction = "v", rot_labels=c(0,90,90))

#Since the p-value that is not less than or equal to 0.05 there is sufficient evidence to conclude that a relationship does not exist between the categorical variables i.e. mother's and father's education and school support.

#Optional Graphs

#Logistic Regression 1 (Mother)
student$schoolsup = as.numeric(student$schoolsup) - 1
student$schoolsup

  ggplot(student, aes(x=Medu, y=schoolsup, color = Mjob)) + 
  theme_bw() + 
  geom_point(position = position_jitter(height = 0.02, width = 0)) +
  stat_smooth(
    method="glm",
    method.args = list(family=binomial), 
    alpha = 0.1, 
    fill = "blue", 
    size = 1, 
    fullrange = TRUE) + 
  ylab("School Support")
  
#Logistic Regression 2 (Father)

ggplot(student, aes(x=Fedu, y=schoolsup, color = Fjob)) + 
  theme_bw() + 
  geom_point(position = position_jitter(height = 0.02, width = 0)) +
  stat_smooth(
    method="glm",
    method.args = list(family=binomial), 
    alpha = 0.1, 
    fill = "blue", 
    size = 1, 
    fullrange = TRUE) + 
  ylab("School Support")

```

